log:
  level: info
  encoding: json

core:
  shutdown_timeout: 10s

storage:
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  dbname: distcomp
  sslmode: disable

redis:
  db: 0
  address: localhost:6379
  user: distcomp
  password: distcomp

api:
  notice_addr: localhost:24130

http:
  port: 24110
  timeout: 5s
  idle_timeout: 60s
