log:
  level: info
  encoding: json

core:
  shutdown_timeout: 10s

storage:
  type: postgres
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  dbname: distcomp
  sslmode: disable

http:
  port: 24110
  timeout: 5s
  idle_timeout: 60s
