services:
  notice:
    image: distcomp/notice
    container_name: notice_api
    restart: unless-stopped

    environment:
      NOTICE_API_CASSANDRA_ADDRS: ${CASSANDRA_ADDRS}
      NOTICE_API_CASSANDRA_KEYSPACE: ${CASSANDRA_KEYSPACE}
      NOTICE_API_CASSANDRA_USER: ${CASSANDRA_USER}
      NOTICE_API_CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
      NOTICE_API_KAFKA_BROKERS: ${KAFKA_BROKERS}
      NOTICE_API_KAFKA_TOPIC: ${KAFKA_TOPIC}

    deploy:
      resources:
        limits: 
          cpus: "0.5"
          memory: 512M

    networks:
      - api_net
      - db_net
      - kafka_net
      
    ports:
      - 24130:24130

    depends_on:
      cassandra:
        condition: service_started

  cassandra:
    image: bitnami/cassandra:5.0.3-debian-12-r5
    container_name: notice_cassandra
    hostname: cassandra
    restart: unless-stopped

    environment:
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_HOST: cassandra
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
      CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER_NAME}
      CASSANDRA_PASSWORD_SEEDER: yes

    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 4G

    networks:
      - db_net

    ports:
      - 9042:9042

    healthcheck:
      test: [ "CMD-SHELL",  "nodetool", "status" ]
      interval: 30s 
      timeout: 20s
      retries: 5
      start_period: 60s

  kafka:
    image: bitnami/kafka:latest
    container_name: notice_kafka
    hostname: kafka
    restart: unless-stopped

    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CLIENT_USERS: admin
      KAFKA_CLIENT_PASSWORDS: admin
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9094
      KAFKA_CFG_LISTENERS: INT://kafka:9092,PLAINTEXT://kafka:9093,CONTROLLER://kafka:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: INT://localhost:9092,PLAINTEXT://kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      ALLOW_PLAINTEXT_LISTENER: yes

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

    networks:
      - kafka_net

    ports:
      - 9092:9092

networks:
  db_net:
  api_net:
  kafka_net:
