services:
  notice:
    image: distcomp/notice
    container_name: notice_api
    restart: unless-stopped

    environment:
      NOTICE_API_CASSANDRA_ADDRS: ${CASSANDRA_ADDRS}
      NOTICE_API_CASSANDRA_KEYSPACE: ${CASSANDRA_KEYSPACE}
      NOTICE_API_CASSANDRA_USER: ${CASSANDRA_USER}
      NOTICE_API_CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}

    deploy:
      resources:
        limits: 
          cpus: "0.5"
          memory: 512M

    networks:
      - api_net
      - db_net
      
    ports:
      - 24130:24130

    depends_on:
      cassandra:
        condition: service_started
        # condition: service_healthy

  cassandra:
    image: bitnami/cassandra:5.0.3-debian-12-r5
    container_name: cassandra_db
    hostname: cassandra
    restart: unless-stopped

    environment:
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
      CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER_NAME}
      CASSANDRA_PASSWORD_SEEDER: yes

    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G

    networks:
      - db_net

    ports:
      - 9042:9042

    # healthcheck:
    #   test: [ "CMD-SHELL", "cqlsh", "-u", "${CASSANDRA_USER}", "-p", "${CASSANDRA_PASSWORD}", "-e", "'describe cluster'"]
    #   interval: 20s 
    #   timeout: 15s
    #   retries: 3
    #   start_period: 30s

networks:
  db_net:
  api_net:
