log:
  level: info
  encoding: json

core:
  shutdown_timeout: 10s

cassandra:
  addrs: localhost:9042
  user: admin
  password: admin
  keyspace: distcomp

kafka:
  brokers: [localhost:9092]
  group_id: distcomp_notice
  topic: notice
  user: admin
  password: admin

http:
  port: 24130
  timeout: 5s
  idle_timeout: 60s

grpc:
  port: 24230
  timeout: 5s
