server:
  address: "localhost:24110"
  note_redirect_base_url: "http://localhost:24130/api/v1.0/notes"

logger:
  level: "info"
  format: "json"
  add_source: false

kafka:
  brokers:
    - "localhost:9092"
  in_topic: "output"
  out_topic: "input"

redis:
  address: "localhost:6379"
  db: 0
