services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "24110:24110"
    depends_on:
      - postgres
    environment:
      PORT: 24110 
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: distcomp  
    # command: >
    #   sh -c "npx typeorm migration:create ./src/migrations/InitMigration && npx typeorm-ts-node-commonjs migration:run -- -d ./src/data-source.ts && node dist/main.js"

  postgres:
    image: postgres:latest
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distcomp
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: