services:
  social-net:
    image: significantnose/social-net:latest  
    build: .
    ports:
      - 24110:24110
      - 24120:24120
      - 24130:24130
      - 24140:24140
      - 24150:24150
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:24110"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.0-alpine
    container_name: db
    restart: unless-stopped

    environment:
      PGPORT: 5432
      POSTGRES_DB: distcomp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - 5432:5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
