server:
  port: 24110
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distcomp
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/master.xml